AUTH0_CLIENT_ID = 'TQjRW5UYhPXTB7YM1YkZjRhYbtOruOhj'
AUTH0_CLIENT_SECRET = 'o0JS29SfjNRFpp1jNSsYXU4fG9A_6PIhqPFu4pzvtgtYPiEIiK0x4tWsHQlbMU0z'
AUTH0_CALLBACK_URL = 'http://mooves.us/callback'
AUTH0_DOMAIN = 'mooves.us.auth0.com'
AUTH0_AUDIENCE = 'https://mooves.us/api'
PROFILE_KEY = 'profile'
SECRET_KEY = 'gutenmade'
JWT_PAYLOAD = 'jwt_payload'
